= DATOM method
Guillame Lecuyer, Clément Levallois <clementlevallois@protonmail.com>
2017-10-22
:revnumber: 1.0
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/java]

The *DATOM* method by Guillaume Lecuyer and Clement Levallois gives guidance to managers of organisations to develop data-centric products and services.

Here you will find the "raw", original content material developed for this methodology.  Use this space if you have questions on this material, or want to submit corrections or suggestions. You will need a Github account.

Visit the main website for the method:

- https://datom-method.github.io/main/ (🇺🇸)
- https://datom-method.github.io/main/index-fr.html (🇫🇷)

== License

- *DATOM is for you to use without restriction in modeling your own or other people's businesses*. If you wish to use the DATOM in original or adapted to sell it as a tool, you must contact the copyright holders, Clément Levallois and Guillaume Lecuyer, for permission.
- Copyright © 2017, Guillaume Lecuyer and Clément levallois


== Contact

Get in touch at datom-method@protonmail.com
