= La méthode DATOM
Guillaume Lecuyer <glecuyer@visiativ.com>;Clément Levallois <levallois@em-lyon.com>
2017-06-19

last modified: {docdate}

:icons!:
:iconsfont:   font-awesome
:revnumber: 1.0
:example-caption!:
ifndef::imagesdir[:imagesdir: ../images]
ifndef::sourcedir[:sourcedir: ../../../main/java]

== Les canvas

<<<<
image::https://docs.google.com/drawings/d/e/2PACX-1vTUqu3_9w338Nmpz5gMVWRaMaJGEhsFBS2cJV_Nigq7xRM9lNZyWyuH_INWzGKxVIXbN647XbJOzplN/pub?w=1440&h=1080[align="center",title="Canevas 01 - Formulation des objectif stratégiques de l'organisation",orientation="landscape",book="keep"]

<<<<

image::https://docs.google.com/drawings/d/e/2PACX-1vTvliO2YHTv65ObEW3A5-YFcgDjw7DniHxsahf1_W3tGVwhTe5aHT-qyMydBe-yzZ1_ApChgX89nCfl/pub?w=1440&h=1080[align="center",title="Canevas 02 - Identification de l'utilisatrice cible du projet",orientation="landscape",book="keep"]


<<<<

image::https://docs.google.com/drawings/d/e/2PACX-1vTm6Hp6PCg4WfGJva-zdxwASTkeyawrSMHNahx956Ga6XiTSiTp9QgDGQl_Sx0Hmx0CYXFVg9SnEMex/pub?w=1440&h=1080[align="center",title="Canevas 03 - Description détaillée de l'utilisateur cible",orientation="landscape",book="keep"]

<<<<
image::https://docs.google.com/drawings/d/e/2PACX-1vTs8EUrU4KQzExlErhBGqIW3EkEtSUJadldJuiIy-MO2M_bFy1sJS6p_yzdZyxH4cKAvoUvUhHavogS/pub?w=1440&h=1080[align="center",title="Canevas 04 - Description des besoins et aspirations de l'utilisatrice cible",orientation="landscape",book="keep"]


<<<<

image::https://docs.google.com/drawings/d/e/2PACX-1vSIhIgqulkB4zVDYNxtaIjjOR4PpLOF_rOpll5ciPYzVJKtMB3hp6A6pcB_qOF8_xKCpHPo8yd0hOl4/pub?w=1440&h=1080[align="center",title="Canevas 05 - Idéation - explora7ion des sources de données potentiellement intéressantes",orientation="landscape",book="keep"]

<<<<

image::https://docs.google.com/drawings/d/e/2PACX-1vS_6PQpzl5FAewV1aOlxERvzM42jXcqEJkot5k_6JZy0wwO2rdFFLcSDmLv6UlAxH24ZcNMDuLDvuSO/pub?w=1440&h=1080[align="center",title="Canevas 06 - Examen détaillé de trois sources des données sélectionnées",orientation="landscape",book="keep"]

<<<<

image::https://docs.google.com/drawings/d/e/2PACX-1vQDO993PzdgVRgYtdTb6LdqMK0p2Ckh3CzvPV6fiDLID5Zk_22TKoMUZ4UxmAPZODbxzq3_5V7rcs8-/pub?w=1440&h=1080[align="center",title="Canevas 07- Aide à la réflexion sur une réponse aub besoins clients",orientation="landscape",book="keep"]

<<<<

image::https://docs.google.com/drawings/d/e/2PACX-1vQ23i0E0x9ouqNLYHcyAyxtZOKSy_xKlHRA7911PraLyxn0LmIednOCskBBTnDY7BO-VPjpiqzvzcXQ/pub?w=1440&h=1080[align="center",title="Canevas 08 - Formalisation de la proposition de valeur",orientation="landscape",book="keep"]

<<<<
image::https://docs.google.com/drawings/d/e/2PACX-1vT_qU9YAaXS1ZWwu4dz9kdAo8v88m6QRaeh6hvn3jqqIoNEixRyY4zV2Dj1uZG-6ljYlVPPq7Zr2cZI/pub?w=1440&h=1080[align="center",title="Canevas 09 - Synthèse quantitative",orientation="landscape",book="keep"]

<<<<


image::https://docs.google.com/drawings/d/e/2PACX-1vRYeankKL0IKg4GIxHQSo_PkN76FZo2pT1OGlENG9n-HFNK-FVAfEUVxg8ON9cWfpWsVxQ3Bs_sFfvg/pub?w=1191&h=1684[align="center",title="Canevas 10 - Synthèse qualitative",book="keep"]

<<<
